name: Issues

on:
  issues:
    types: [opened, labeled]

permissions:
  # Auto hash fixing commits
  contents: write
  issues: write

concurrency:
  group: issue-${{ github.event.issue.number }}
  cancel-in-progress: true

jobs:
  issueHandler:
    name: IssueHandler
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: IssueHandler
        uses: ScoopInstaller/GithubActions@a709983c0692a8a853c288cf5e9bf14658107936 # main as of 2026-08-06
        if: github.event.action == 'opened' || (github.event.action == 'labeled' && contains(github.event.issue.labels.*.name, 'verify'))
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
